---
title: "LOSO-CV Results"
output: 
  html_document: 
    toc: yes
    fig_width: 20
    fig_height: 10
    fig.retina: 2
    device: ragg::agg_png
    self_contained: no
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(acceleep)
library(ggplot2)
library(dplyr)
library(tidyr)
library(kableExtra)

theme_set(hrbrthemes::theme_ipsum_ps())
```

```{r read-data}
# Iterate over all model output folders, read in latest CV runs, bind together
cv_results <- purrr::map_df(
  here::here("output/cross-validation", c("LM", "RF", "DNN", "CNN", "RNN")),
  ~read_cv_results(.x, latest_only = TRUE)
)

cv_results_full <- purrr::map_df(
  here::here("output/cross-validation", c("LM", "RF", "DNN", "CNN", "RNN")),
  ~read_cv_results(.x, latest_only = FALSE)
)

cv_results_full %>%
  group_by(model_kind, timestamp, outcome_unit) %>%
  summarize(mean_mean_rmse = mean(mean_rmse), .groups = "drop") %>%
  group_by(model_kind, outcome_unit) %>%
  slice_min(mean_mean_rmse, n = 1) %>%
  pivot_wider(
    id_cols = c(model_kind, timestamp, outcome_unit), 
    names_from = outcome_unit,
    values_from = mean_mean_rmse
  ) %>%
  kable(caption = "Best model by unit with RMSE (non-unique)") %>%
  kable_styling()
```

## Boxplot by Accelerometer

```{r boxplot-by-accelerometer}
cv_results %>%
  tidyr::unnest(data) %>%
  ggplot(aes(x = reorder(model_kind, rmse), y = rmse)) +
  facet_grid(cols = vars(accel), rows = vars(outcome_unit), scales = "free_y") +
  geom_point(size = 1, alpha = .2, position = position_jitter(width = .15, seed = 23)) +
  geom_boxplot(alpha = .5, outlier.alpha = 0) +
  stat_summary(geom = "point", fun = mean, fill = "white", shape = 21, color = "black", size = 2) +
  labs(
    title = "Leave-One-Subject-Out Cross Validation",
    subtitle = "Across all subjects in the respective training set (2/3 of complete data)",
    x = "Model Type", y = "Per-Subject RMSE (Quartiles + Mean)"
  ) +
  hrbrthemes::theme_ipsum_ps(grid = "Y")


# ggsave(filename = here::here("LOSO-CV-boxplot-20200907.pdf"), device = cairo_pdf, scale = 2, width = 10, height = 5)
```

```{r boxplot-by-unit-accel}
cv_results %>%
  tidyr::unnest(data) %>%
  ggplot(aes(y = reorder(accel, -rmse), x = rmse)) +
  facet_grid(rows = vars(model_kind), cols = vars(outcome_unit), scales = "free") +
  geom_point(size = 1, alpha = .2, position = position_jitter(width = .01, seed = 23)) +
  geom_boxplot(alpha = .5, outlier.alpha = 0) +
  stat_summary(geom = "point", fun = mean, fill = "white", shape = 21, color = "black", size = 2) +
  labs(
    title = "Leave-One-Subject-Out Cross Validation",
    subtitle = "Across all subjects in the respective training set (2/3 of complete data)",
    y = "Accelerometer", x = "Per-Subject RMSE (Quartiles + Mean)"
  ) +
  hrbrthemes::theme_ipsum_ps(grid = "X")
```


```{r boxplot-by-unit}
cv_results %>%
  tidyr::unnest(data) %>%
  ggplot(aes(y = reorder(model_kind, -rmse), x = rmse)) +
  facet_grid(rows = vars(accel), cols = vars(outcome_unit), scales = "free_x") +
  geom_point(size = 1, alpha = .2, position = position_jitter(width = .05, seed = 23)) +
  geom_boxplot(alpha = .5, outlier.alpha = 0) +
  stat_summary(geom = "point", fun = mean, fill = "white", shape = 21, color = "black", size = 2) +
  labs(
    title = "Leave-One-Subject-Out Cross Validation",
    subtitle = "Across all subjects in the respective training set (2/3 of complete data)",
    y = "Model Type", x = "Per-Subject RMSE (Quartiles + Mean)"
  ) +
  hrbrthemes::theme_ipsum_ps(grid = "Y")
```

```{r meanci-by-unit}
cv_results %>%
  tidyr::unnest(data) %>%
  ggplot(aes(y = reorder(model_kind, -rmse), x = rmse)) +
  facet_grid(rows = vars(accel), cols = vars(outcome_unit), scales = "free_x") +
  stat_summary(geom = "errorbar", fun.data = "mean_cl_boot")  +
  stat_summary(geom = "point", fun = mean, fill = "white", shape = 21, color = "black", size = 2) +
  labs(
    title = "Leave-One-Subject-Out Cross Validation",
    subtitle = "Across all subjects in the respective training set (2/3 of complete data)",
    y = "Model Type", x = "Per-Subject RMSE (Mean + Bootstrap-CI)"
  ) +
  hrbrthemes::theme_ipsum_ps(grid = "Y")
```


## Tables

```{r table-by-accel}
cv_results %>%
  transmute(
    model_kind = model_kind,
    accel = accel,
    outcome_unit = outcome_unit,
    measure = glue::glue("{round(mean_rmse, 2)} ({round(sd_rmse, 2)})") %>% as.character()
  ) %>%
  tidyr::pivot_wider(names_from = accel, values_from = measure) %>%
  rename(Model = model_kind, Outcome = outcome_unit) %>%
  kable(caption = glue::glue("LOSO-CV results, Mean RMSE (SD)")) %>%
  kable_styling() %>%
  collapse_rows(columns = 1)
```

```{r table-by-model}
cv_results %>%
  mutate(
    measure = glue::glue("{round(mean_rmse, 2)} ({round(sd_rmse, 2)})") %>% as.character()
  ) %>%
  group_by(accel, outcome_unit) %>%
  mutate(
    # min_rmse = min(mean_rmse),
    is_min_mean_rmse = mean_rmse == min(mean_rmse)
  ) %>%
  ungroup() %>%
  select(
    model_kind,
    accel,
    outcome_unit,
    measure,
    is_min_mean_rmse
  ) %>%
  mutate(measure = cell_spec(measure, bold = is_min_mean_rmse)) %>%
  select(-is_min_mean_rmse) %>%
  pivot_wider(id_cols = c(model_kind, accel, outcome_unit), names_from = model_kind, values_from = measure) %>%
  rename(Accelerometer = accel, Outcome = outcome_unit) %>%
  kable(
    caption = glue::glue("LOSO-CV results: Mean RMSE (SD)"), escape = FALSE
  ) %>%
  kable_styling() %>%
  collapse_rows(columns = 1) %>%
  footnote(general_title = "Bold:", general = "Minimal RMSE per Row (Accelerometer and Outcome)")
```


## CNNs

```{r cnn-results-boxplot}
# By accelerometer (flipped)
cv_results_full %>%
  filter(model_kind == "CNN") %>%
  tidyr::unnest(data) %>%
  ggplot(aes(y = reorder(model_spec, -rmse), x = rmse)) +
  facet_grid(rows = vars(accel), cols = vars(outcome_unit), scales = "free") +
  geom_point(size = 1, alpha = .2, position = position_jitter(width = .15, seed = 23)) +
  geom_boxplot(alpha = .5, outlier.alpha = 0) +
  stat_summary(geom = "point", fun = mean, fill = "red", shape = 21, color = "black", size = 2) +
  labs(
    title = "Leave-One-Subject-Out Cross Validation",
    subtitle = "Across all subjects in the respective training set (2/3 of complete data)",
    y = "Model", x = "Per-Subject RMSE (+ Mean)"
  ) +
  hrbrthemes::theme_ipsum_pub(grid = "X")
```

Table with mean'd accelerometers, quick glance at "best overall" model ranking

```{r cnn-results-table}
cv_results_full %>%
  filter(model_kind == "CNN") %>%
  tidyr::unnest(data) %>%
  group_by(timestamp, model_spec, outcome_unit) %>%
  summarize(
    mean_rmse = mean(rmse),
    sd_rmse = sd(rmse),
    .groups = "drop"
  ) %>%
  tidyr::pivot_wider(
    id_cols = c(timestamp, model_spec, outcome_unit),
    names_from = outcome_unit, values_from = c(mean_rmse, sd_rmse)
  ) %>%
  arrange(mean_rmse_kJ) %>%
  kable() %>%
  kable_styling()
```

```{r cnn-results-aggregated-meanci}
cv_results_full %>%
  filter(model_kind == "CNN") %>%
  tidyr::unnest(data) %>%
  group_by(model_spec, outcome_unit) %>%
  summarize(
    y = mean(rmse),
    ymin = y - sd(rmse),
    ymax = y + sd(rmse),
    .groups = "drop"
  ) %>%
  ggplot(aes(x = reorder(model_spec, -y), y = y)) +
  coord_flip() +
  facet_grid(cols = vars(outcome_unit), scales = "free") +
  geom_errorbar(aes(ymin = ymin, ymax = ymax), size = 2, width = .5) +
  geom_point(shape = 21, color = "darkgray", fill = "white", size = 4) +
  labs(
    title = "Leave-One-Subject-Out Cross Validation",
    subtitle = "Across all subjects in the respective training set (2/3 of complete data)\nAveraged over accelerometers",
    x = "Model Spec", y = "Per-Subject RMSE (Mean +- SD)"
  ) +
  hrbrthemes::theme_ipsum_pub(grid = "X")
```


## DNNs

```{r dnn-results-boxplot}
cv_results_full %>%
  filter(model_kind == "DNN") %>%
  tidyr::unnest(data) %>%
  ggplot(aes(y = reorder(model_spec, -rmse), x = rmse)) +
  facet_grid(rows = vars(accel), cols = vars(outcome_unit), scales = "free") +
  geom_point(size = 1, alpha = .2, position = position_jitter(width = .15, seed = 23)) +
  geom_boxplot(alpha = .5, outlier.alpha = 0) +
  stat_summary(geom = "point", fun = mean, fill = "red", shape = 21, color = "black", size = 2) +
  labs(
    title = "Leave-One-Subject-Out Cross Validation",
    subtitle = "Across all subjects in the respective training set (2/3 of complete data)",
    y = "Model", x = "Per-Subject RMSE (+ Mean)"
  ) +
  hrbrthemes::theme_ipsum_pub(grid = "X")
```

Table with mean'd accelerometers, quick glance at "best overall" model ranking

```{r dnn-results-table}
cv_results_full %>%
  filter(model_kind == "DNN") %>%
  tidyr::unnest(data) %>%
  group_by(timestamp, model_spec, outcome_unit) %>%
  summarize(
    mean_rmse = mean(rmse),
    sd_rmse = sd(rmse),
    .groups = "drop"
  ) %>%
  tidyr::pivot_wider(
    id_cols = c(timestamp, model_spec, outcome_unit),
    names_from = outcome_unit, values_from = c(mean_rmse, sd_rmse)
  ) %>%
  arrange(mean_rmse_kJ) %>%
  kable() %>%
  kable_styling()
```

## RNNs

```{r rnn-results-boxplot}
cv_results_full %>%
  filter(stringr::str_detect(model_kind, "^RNN")) %>%
  tidyr::unnest(data) %>%
  mutate(res = glue::glue("{res}Hz")) %>%
  ggplot(aes(y = reorder(model_spec, -rmse), x = rmse, color = res, fill = res)) +
  facet_grid(rows = vars(accel), cols = vars(outcome_unit), scales = "free") +
  geom_point(size = 1, alpha = .2, position = position_jitter(width = .15, seed = 23)) +
  geom_boxplot(alpha = .25, outlier.alpha = 0) +
  stat_summary(geom = "point", fun = mean, fill = "red", shape = 21, color = "black", size = 2) +
  scale_color_brewer(palette = "Dark2", aesthetics = c("color", "fill")) +
  labs(
    title = "Leave-One-Subject-Out Cross Validation",
    subtitle = "Across all subjects in the respective training set (2/3 of complete data)",
    y = "Model", x = "Per-Subject RMSE (+ Mean)"
  ) +
  hrbrthemes::theme_ipsum_pub(grid = "X") +
  theme(legend.position = "top")
```

# Model Runtime

Model runtime summaries (seconds)

```{r runtime}
cv_results_full %>%
  unnest(data) %>%
  filter(!is.na(model_took)) %>%
  group_by(model_kind) %>%
  summarize(
    mean_took = mean(model_took, na.rm = TRUE),
    sd_took =  sd(model_took, na.rm = TRUE),
    range_took = paste0(range(model_took), collapse = " – "),
    .groups = "drop"
  ) %>%
  kable(digits = 2, caption = "Model runtimes") %>%
  kable_styling()

```

